Add CFP & Tickets links for 2022
barcelonajug/jbcnconf_web pull request #1033
Opened 2021-12-29 16:16 UTC by abelsromero

2021-12-29 16:16 UTC, abelsromero commented on 2022/_data/homepage.json
> +  "cfp_closing": "18th of May (last day)",
TBC

2021-12-29 16:28 UTC, anyulled approved these changes

2021-12-31 09:18 UTC, icougil requested changes
Some suggestions

2021-12-31 09:18 UTC, icougil commented on 2022/_data/homepage.json
> +  "tickets_url": "https://tickets.jbcnconf.com/event/2022",
The main URL should work (once we publish the event):
```suggestion
  "tickets_url": "https://tickets.jbcnconf.com/",
```

2021-12-31 09:18 UTC, icougil commented on 2022/_data/homepage.json
> +  "cfp_closing": "18th of May (last day)",
```suggestion
  "cfp_closing": "30th of April (last day)",
```

2021-12-31 16:50 UTC, merged