Publish Noa, Andzrej and Andres
barcelonajug/jbcnconf_web pull request #1112
Opened 2022-04-20 19:56 UTC by icougil

2022-04-20 20:25 UTC, abelsromero requested changes

2022-04-20 20:25 UTC, abelsromero commented on 2022/_data/talks.json
> +      "abstract": "It's 2022, long gone are the days of ceremony and Java development should be productivity, simplicity.\n\nLet's look at how we make it happen, in context of startup going FAST.\nI
El abstract no está formateado, ojo q se haya generado en html 
![image](https://user-images.githubusercontent.com/5781153/164316619-990e6230-2272-4cfe-b98e-26718084626c.png)

2022-04-20 20:27 UTC, anyulled approved these changes
I understand that the code deletion is regarding some duplicated code, right?

2022-04-20 20:48 UTC, icougil commented
> I understand that the code deletion is regarding some duplicated code, right?

yep, you can compare it side by side to double check it, but yes it is basically because of the things that git does (don't know why the content it is moved)

2022-04-20 20:51 UTC, icougil commented on 2022/_data/talks.json
> +      "abstract": "It's 2022, long gone are the days of ceremony and Java development should be productivity, simplicity.\n\nLet's look at how we make it happen, in context of startup going FAST.\nI
macho... esto ya está en main...

2022-04-20 20:57 UTC, icougil commented on 2022/_data/talks.json
> +      "abstract": "It's 2022, long gone are the days of ceremony and Java development should be productivity, simplicity.\n\nLet's look at how we make it happen, in context of startup going FAST.\nI
hecho

2022-04-21 12:06 UTC, abelsromero commented
> yep, you can compare it side by side to double check it, but yes it is basically because of the things that git does (don't know why the content it is moved)

My theory is at some point some manual edit was done or some rebase from gh-pages.

2022-04-21 13:49 UTC, icougil commented
@abelsromero do the changes look good now?

2022-04-21 18:38 UTC, merged